### ISSUE TITLE
Port from GConf to Gio.Settings

### ISSUE THREAD

**Issue by quozl** [sugarlabs/activity-turtle-flags#1]
https://github.com/sugarlabs/activity-turtle-flags/blob/ac20359849272efa9c1978d979218b5782c21523/collaboration/buddy.py#L98

**Comment by yashagrawal3** [comment]
Will be working on this activity in a similar fashion as Turtle Confusion, once the PR in it gets merged.

**Comment by quozl** [comment]
Thanks!

After that, you will be in a good position to assess if the repositories can be recombined in order to generate three different bundles from the same repository, or make the unique features a menu option in the main repository.  i.e. the reverse of project forking.
