### ISSUE TITLE
Rebase and merge with Turtle Art

### ISSUE THREAD

**Issue by quozl** [sugarlabs/activity-turtle-flags#4]
Much common code.

**Comment by vipulgupta2048** [comment]
Honestly, @quozl I get very confused about all the turtle~ activities sometimes. I mean, aren't all of them same except a few tweaks. I may be wrong, I dunno.

**Comment by walterbender** [comment]
They share much of the same code, but present slightly different configurations to specific audiences. It certainly would be better to consolidate them to some degree.
